### PR TITLE
one-click auto generates animation keyframes

### PR DESCRIPTION
**Pull request by cpuwolf**
#186 enhancement ticket
1. add a box UI in object tab
2. add operator for action
3. add 3 props in scene

### CODE REVIEW

**Comment by cpuwolf** [comment]
above check error is not from mine

**Comment by der-On** [comment]
This adds a new keyframe on each frame? I think this might not be optimal. Maybe something like blenders auto-keyframing would be better? I'm yet not yet sure how auto-keyframing exactly works under the hoods.

I can however imagine this living as a seperate addon on top of XP2B.

**Comment by cpuwolf** [comment]
no, not each frame, you can define frame step. but if you want to have each frame, it would be OK.  I don' think Blender auto-keyframing works as you expect, that is why Blender provides tool bar on the left of UI to give insert keyframe. this change is highly depends on XP2B dataref f-curve animation. I don' think I can do it on top of XP2B

**Comment by tngreene** [comment]
(I am fully aware of how long this has sat around collecting dust. The more I waited to say something after I took over the project the more I decided to put it off! I apologize though I'm guessing you've probably forgotten about this by now.) I'm sorry to say that as the project currently stands in 2020, this isn't a feature that will get merged or developed. However, I hope it has been useful to you and again, sorry it was ignored for a long time. Best wishes, Ted

**Pull request closed without merging**
