### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by outbaacker**
You should remove the notice saying that there was no importer, since the addition of one in 4.20

### CODE REVIEW

**Review by tngreene — CHANGES_REQUESTED** [review]
Could you add something like. "An experimental importer can be found on [branch link]". Thanks!

**Comment by tngreene** [comment]
I know I could do that quickly but its fun to get a conversation started.

**Comment by outbaacker** [comment]
Will do!

**Comment by tngreene** [comment]
Thank you! Are you interested in solving other bugs?

**Pull request merged**
